
# POST http://localhost:8080/openct/marking/score/test/display HTTP/1.1
# Content-Type: application/json

# {
#     "testId":"1"
# }

# POST http://localhost:8080/openct/marking/score/test/list HTTP/1.1
# Content-Type: application/json

# {
#     "userId":"100"
# }

# POST http://localhost:8080/openct/marking/score/test/point HTTP/1.1
# Content-Type: application/json

# {
#     "userId":"10000",
#     "scores": "6",
#     "testId":"6",
#     "testDetailId": "12"
# }

# POST http://localhost:8080/openct/marking/score/test/problem HTTP/1.1
# Content-Type: application/json

# {
#     "userId":"102",
#     "problemType": "2",
#     "testId":"1"
# }

# POST http://localhost:8080/openct/marking/score/test/answer HTTP/1.1
# Content-Type: application/json

# {
#     "userId":"101",
#     "testId":"1"
# }

# POST http://localhost:8080/openct/marking/score/test/example/detail HTTP/1.1
# Content-Type: application/json

# {
#     "userId":"101",
#     "exampleTestId":"1"
# }

# POST http://localhost:8080/openct/marking/score/test/example/list HTTP/1.1
# Content-Type: application/json

# {
#     "userId":"101",
#     "testId":"1"
# }

# POST http://localhost:8080/openct/marking/score/test/review HTTP/1.1
# Content-Type: application/json

# {
#     "userId":"101"
# }

# POST http://localhost:8080 HTTP/1.1
# Content-Type: application/json

# {
#     "name":"100"
# }